// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveSessions():Promise<Array<string>>;

export function CancelStream(arg1:string,arg2:boolean):Promise<boolean>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;
