// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveSessions() {
  return window['go']['main']['App']['ActiveSessions']();
}

export function CancelStream(arg1, arg2) {
  return window['go']['main']['App']['CancelStream'](arg1, arg2);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}
